# Generated by Django 2.1.2 on 2018-10-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreports',
            name='content',
            field=models.TextField(default='a', verbose_name='工作内容'),
            preserve_default=False,
        ),
    ]
