# Generated by Django 2.1.2 on 2018-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_dailyreports_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.CharField(default='陈翌', max_length=32, verbose_name='开发'),
            preserve_default=False,
        ),
    ]
