# Generated by Django 2.1.2 on 2018-10-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_project_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreports',
            name='week',
            field=models.IntegerField(verbose_name='星期'),
        ),
    ]
