# Generated by Django 2.1.2 on 2018-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_auto_20181030_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreports',
            name='project',
            field=models.CharField(max_length=64, verbose_name='项目名称'),
        ),
    ]
