# Generated by Django 2.1.2 on 2018-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_auto_20181030_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreports',
            name='creator',
            field=models.CharField(default='1', max_length=32, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=32, unique=True, verbose_name='显示用户名'),
        ),
    ]
