# Generated by Django 2.1.2 on 2018-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_auto_20181030_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='emailpasswd',
            field=models.CharField(default='a', max_length=100, verbose_name='邮箱密码'),
            preserve_default=False,
        ),
    ]
