# Generated by Django 2.1.2 on 2018-10-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_myuser_emailpasswd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='nickname',
        ),
    ]
